package copy

// These types were autogenerated by snapshotting existing types using github.com/antonvlasov/type-snapshot/pkg/generator
type (
	PkgbBOld []int

	Main_pkgAOld struct {
		value string
	}

	Main_pkgMainStructOld struct {
		Field1 PkgaAOld
		Field2 PkgbAOld
		field3 PkgbBOld
		field4 Main_pkgAOld
	}

	PkgaAOld struct {
		value int
	}

	PkgbAOld struct {
		value int
	}

	PkgbUnUsedAOld struct {
		field string
	}

	PkgbUnUsedBOld struct {
		field string
	}
)
