package copy

// These types were autogenerated by snapshotting existing types using github.com/antonvlasov/type-snapshot
type (
	Element2Old map[string]*[]int

	Element1Old struct {
		ElementField1 int `json:"int"`
	}

	TopStructOld struct {
		Field1 string      `json:"field1"`
		Field2 Element1Old `json:"field2"`
		Field3 Element2Old `json:"field3"`
	}
)
